apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ubswqfxlo-nodejs 
  janus-idp.io/tekton: ubswqfxlo-nodejs
  backstage.io/kubernetes-id: ubswqfxlo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ubswqfxlo-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml